"""Versioned CoFL-S augmentation defaults, independent of asset locations."""

DEFAULT_AUGMENTATION = {
    "stop_radius_m": 1.0,
    "bev_x_max": 5.0,
    "bev_resolution": 0.1,
    "v_norm": 5.0,
    "hfov_rad": 1.5707963267948966,
    "semantic_anchor": {
        "min_visible_pixels": 150,
        "min_dist_m": 0.3,
        "max_dist_m": 8.0,
        "max_geo_euc_ratio": 2.5,
        "whitelist": [
            "chair",
            "table",
            "bed",
            "sofa",
            "cabinet",
            "sink",
            "toilet",
            "bathtub",
            "shower",
            "cushion",
            "plant",
            "mirror",
            "shelving",
            "chest_of_drawers",
            "counter",
            "stool",
            "fireplace",
            "tv_monitor",
            "picture",
            "towel",
            "appliances",
            "lighting",
            "seating",
            "railing",
            "curtain",
        ],
        "blacklist": [
            "wall",
            "floor",
            "ceiling",
            "door",
            "stairs",
            "window",
            "misc",
            "void",
            "objects",
            "furniture",
            "unknown",
            "remove",
            "beam",
            "column",
            "blinds",
            "board_panel",
        ],
        "region_visible_pixel_blacklist": [
            "wall",
            "door",
            "window",
            "misc",
            "void",
            "unknown",
            "remove",
        ],
    },
    "alternative_sampler": {
        "K": 4,
        "object_min_visible_pixels_strict": 500,
        "object_pair_bypass_min_pixels": 100,
        "object_navmesh_projection_max_m": 1.0,
        "go_past_geo_excess_min_m": 1.0,
        "go_past_path_through_obj_tol_m": 0.5,
        "forward_r_min_m": 1.0,
        "forward_r_max_m": 3.0,
        "forward_theta_half_rad": 0.0872664626,
        "forward_corridor_step_m": 0.1,
        "forward_max_sample_attempts": 8,
        "region_n_sample_pts": 16,
        "region_max_geo_m": 15.0,
        "region_forward_angle_deg": 15.0,
        "region_openness_search_radius_m": 2.0,
        "region_center_dist_weight": 1.0,
        "region_min_visible_pixels_strict": 1000,
        "framing_probs": {"plain_turn": 0.5, "combined": 0.2, "plain_enter": 0.3},
        "terminal_alt_prob": 0.005,
        "families_enabled": {
            "toward_object": True,
            "go_past": True,
            "forward": False,
            "terminal": True,
            "region_enter": True,
            "turn_left_enter": True,
            "turn_right_enter": True,
            "exit_enter": True,
            "turn_left_exit_enter": True,
            "turn_right_exit_enter": True,
            "turn_left": True,
            "turn_right": True,
        },
        "prioritize_families": [
            "region_enter",
            "turn_left_enter",
            "turn_right_enter",
            "exit_enter",
            "turn_left_exit_enter",
            "turn_right_exit_enter",
            "turn_left",
            "turn_right",
        ],
        "backup_alt_pool_size": 3,
    },
    "flow_field_generator": {
        "safe_radius_cells": 5.0,
        "safety_cost_weight": 1.0,
        "goal_weight": 1.0,
        "obs_weight": 5.0,
        "global_geodesic_res": None,
        "global_geodesic_margin_m": 1.5,
        "smoothing_iters": 0,
        "smooth_ksize": 5,
        "smooth_sigma": 0.5,
        "traj_smooth_sigma": 1.5,
        "escape_canon_speed": 1.0,
        "depth_visibility_tol_m": 0.1,
    },
    "dataset_builder": {
        "max_steps_per_ep": 500,
        "frame_stride": 1,
        "baseline_labels": {"horizon": 100},
    },
}
