/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runtime/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Studio */
        post: operations["close_studio_api_v1_runtime_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runtime/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Device */
        get: operations["runtime_device_api_v1_runtime_device_get"];
        put?: never;
        /** Select Device */
        post: operations["select_device_api_v1_runtime_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource Browser */
        get: operations["resource_browser_api_v1_resources_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Resource */
        post: operations["register_resource_api_v1_resources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{kind}/{resource_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Resource */
        post: operations["activate_resource_api_v1_resources__kind___resource_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenes/{scene_id}/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scene Asset */
        get: operations["scene_asset_api_v1_scenes__scene_id__asset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/samples/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Sample */
        get: operations["dataset_sample_api_v1_datasets__dataset_id__samples__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_api_v1_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Benchmarks */
        get: operations["benchmarks_api_v1_domains_ego2d_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/benchmarks/{benchmark_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Episodes */
        get: operations["episodes_api_v1_domains_ego2d_benchmarks__benchmark_id__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/benchmarks/{benchmark_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenes */
        get: operations["scenes_api_v1_domains_ego2d_benchmarks__benchmark_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_domains_ego2d_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active Session */
        get: operations["active_session_api_v1_domains_ego2d_sessions_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_v1_domains_ego2d_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Session */
        post: operations["stop_session_api_v1_domains_ego2d_sessions__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Command Session */
        post: operations["command_session_api_v1_domains_ego2d_sessions__session_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Session */
        post: operations["pause_session_api_v1_domains_ego2d_sessions__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Session */
        post: operations["resume_session_api_v1_domains_ego2d_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/ego2d/sessions/{session_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Session */
        post: operations["reset_session_api_v1_domains_ego2d_sessions__session_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BenchmarkDescriptor */
        BenchmarkDescriptor: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Domain Id */
            domain_id?: string | null;
        };
        /** BrowseEntry */
        BrowseEntry: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Is Dir */
            is_dir: boolean;
            /** Selectable */
            selectable: boolean;
        };
        /** BrowseShortcut */
        BrowseShortcut: {
            /**
             * Id
             * @enum {string}
             */
            id: "cwd" | "home" | "filesystem";
            /** Label */
            label: string;
            /** Path */
            path: string;
        };
        /** Catalog */
        Catalog: {
            /**
             * Api Version
             * @default 1
             * @constant
             */
            api_version?: "1";
            /** Domains */
            domains: components["schemas"]["DomainDescriptor"][];
            /** Modes */
            modes: components["schemas"]["ModeDescriptor"][];
            /** Models */
            models: components["schemas"]["ModelDescriptor"][];
            /** Datasets */
            datasets: components["schemas"]["DatasetDescriptor"][];
            /** Scenes */
            scenes: components["schemas"]["SceneDescriptor"][];
            /** Benchmarks */
            benchmarks: components["schemas"]["BenchmarkDescriptor"][];
            /** Device */
            device: string;
        };
        /** DatasetDescriptor */
        DatasetDescriptor: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Split
             * @default val
             */
            split?: string;
            /** Profile */
            profile?: string | null;
            /** Domain Id */
            domain_id?: string | null;
        };
        /** DatasetView */
        DatasetView: {
            /** Dataset Id */
            dataset_id: string;
            /** Split */
            split: string;
            /** Observation Id */
            observation_id: string;
            /** Index */
            index: number;
            /** Count */
            count: number;
            /** Sample Id */
            sample_id: string;
            /** Profile */
            profile: string;
            /** Instruction */
            instruction: string;
            /** Image */
            image: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Start */
            start: [
                number,
                number
            ];
            /** Coordinate Frame */
            coordinate_frame: string;
            /** Coordinate Unit */
            coordinate_unit: string;
            /** Vector Unit */
            vector_unit: string;
            /** Queries */
            queries: [
                number,
                number
            ][];
            /** Vectors */
            vectors: [
                number,
                number
            ][];
            /** Trajectory */
            trajectory?: [
                number,
                number
            ][] | null;
            /** Target Action */
            target_action?: number | null;
            /** Supervised Count */
            supervised_count: number;
            /** Preview Count */
            preview_count: number;
        };
        /** DeviceFailure */
        DeviceFailure: {
            /** Id */
            id: string;
            /** Device */
            device: string;
            /** Message */
            message: string;
        };
        /** DeviceSelection */
        DeviceSelection: {
            /** Device */
            device: string;
        };
        /** DomainDescriptor */
        DomainDescriptor: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Methods */
            methods: string[];
            /** Profiles */
            profiles: string[];
            /** Resource Kinds */
            resource_kinds?: ("model" | "dataset" | "benchmark")[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** FloorSpec */
        FloorSpec: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Elevation */
            elevation: number;
            /** Min Height */
            min_height: number;
            /** Max Height */
            max_height: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModeDescriptor */
        ModeDescriptor: {
            /** Id */
            id: string;
            /** Domain Id */
            domain_id: string;
            /** Task */
            task: string;
            /**
             * Execution
             * @enum {string}
             */
            execution: "static" | "session";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Renderer */
            renderer: string;
            /** Capabilities */
            capabilities?: string[];
            /** Default Parameters */
            default_parameters?: {
                [key: string]: unknown;
            };
        };
        /** ModelDescriptor */
        ModelDescriptor: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Method */
            method?: string | null;
            /** Profile */
            profile?: string | null;
            /** Domain Id */
            domain_id?: string | null;
        };
        /** OnlineBenchmark */
        OnlineBenchmark: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Available */
            available: boolean;
            /** Reason */
            reason?: string | null;
            /** Benchmark Reason */
            benchmark_reason?: string | null;
            /**
             * Episode Count
             * @default 0
             */
            episode_count?: number;
            /**
             * Split
             * @default val_unseen
             */
            split?: string;
        };
        /** OnlineCommand */
        OnlineCommand: {
            /** Instruction */
            instruction: string;
        };
        /** OnlineEpisode */
        OnlineEpisode: {
            /** Index */
            index: number;
            /** Episode Id */
            episode_id: string;
            /** Scene Id */
            scene_id: string;
            /** Instruction */
            instruction: string;
        };
        /** OnlineEpisodePage */
        OnlineEpisodePage: {
            /** Items */
            items: components["schemas"]["OnlineEpisode"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** OnlineObservation */
        OnlineObservation: {
            /** Image */
            image: string;
            /** T Sim S */
            t_sim_s: number;
            /** Position */
            position: [
                number,
                number,
                number
            ];
            /** Rotation */
            rotation: [
                number,
                number,
                number,
                number
            ];
        };
        /** OnlineReset */
        OnlineReset: {
            /** Start Position */
            start_position?: [
                number,
                number,
                number
            ] | null;
            /** Start Yaw Deg */
            start_yaw_deg?: number | null;
            /** Instruction */
            instruction?: string | null;
        };
        /** OnlineScene */
        OnlineScene: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Scene Id */
            scene_id: string;
            /** Spawn Position */
            spawn_position?: [
                number,
                number,
                number
            ] | null;
            /**
             * Spawn Yaw Deg
             * @default 0
             */
            spawn_yaw_deg?: number;
        };
        /** OnlineScenePage */
        OnlineScenePage: {
            /** Items */
            items: components["schemas"]["OnlineScene"][];
            /** Total */
            total: number;
        };
        /** OnlineSession */
        OnlineSession: {
            /** Id */
            id: string;
            /**
             * Domain Id
             * @default ego2d
             * @constant
             */
            domain_id?: "ego2d";
            /**
             * Mode Id
             * @default ego2d-playground
             * @enum {string}
             */
            mode_id?: "ego2d-playground" | "ego2d-interactive";
            /**
             * Mode
             * @default benchmark
             * @enum {string}
             */
            mode?: "benchmark" | "interactive";
            /** Benchmark Id */
            benchmark_id: string;
            /** Model Id */
            model_id: string;
            /** Episode Index */
            episode_index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "running" | "waiting" | "paused" | "stopping" | "completed" | "cancelled" | "failed";
            /**
             * Scene Id
             * @default
             */
            scene_id?: string;
            /** Current Position */
            current_position?: [
                number,
                number,
                number
            ] | null;
            /** Current Yaw Deg */
            current_yaw_deg?: number | null;
            observation?: components["schemas"]["OnlineObservation"] | null;
            /** Command State */
            command_state?: {
                [key: string]: unknown;
            };
            /** Active Instruction */
            active_instruction?: {
                [key: string]: unknown;
            } | null;
            /** Command Log */
            command_log?: {
                [key: string]: unknown;
            }[];
            /**
             * Epoch
             * @default 0
             */
            epoch?: number;
            /** Reason */
            reason?: string | null;
            /** Steps */
            steps?: components["schemas"]["OnlineStep"][];
            /**
             * Total Steps
             * @default 0
             */
            total_steps?: number;
            /**
             * First Available Step
             * @default 0
             */
            first_available_step?: number;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Reference Path */
            reference_path?: [
                number,
                number
            ][];
            /** Goal Position */
            goal_position?: [
                number,
                number,
                number
            ] | null;
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            };
        };
        /** OnlineSessionRequest */
        OnlineSessionRequest: {
            /** Benchmark Id */
            benchmark_id: string;
            /** Model Id */
            model_id: string;
            /**
             * Mode
             * @default benchmark
             * @enum {string}
             */
            mode?: "benchmark" | "interactive";
            /** Scene Id */
            scene_id?: string | null;
            /** Start Position */
            start_position?: [
                number,
                number,
                number
            ] | null;
            /** Start Yaw Deg */
            start_yaw_deg?: number | null;
            /**
             * Instruction
             * @default
             */
            instruction?: string;
            /** Instruction Mode */
            instruction_mode?: ("oracle" | "full_instruction") | null;
            /**
             * Episode Index
             * @default 0
             */
            episode_index?: number;
            /**
             * Max Time S
             * @default 120
             */
            max_time_s?: number;
            /**
             * Max Steps
             * @default 500
             */
            max_steps?: number;
            /**
             * Plant Hz
             * @default 100
             */
            plant_hz?: number;
            /**
             * Controller Hz
             * @default 50
             */
            controller_hz?: number;
            /**
             * Sensor Hz
             * @default 30
             */
            sensor_hz?: number;
            /**
             * Planner Hz
             * @default 5
             */
            planner_hz?: number;
            /**
             * Policy Steps
             * @default 100
             */
            policy_steps?: number;
            /** Policy Dt */
            policy_dt?: number | null;
            /**
             * Field Grid Size
             * @default 100
             */
            field_grid_size?: number;
            /**
             * Field Query Chunk Size
             * @default 4096
             */
            field_query_chunk_size?: number;
            /**
             * Stop Threshold
             * @default 0
             */
            stop_threshold?: number;
            /**
             * Stop Endpoint M
             * @default 0.2
             */
            stop_endpoint_m?: number;
            /**
             * Stop Pool Step
             * @default 0.5
             */
            stop_pool_step?: number;
            /**
             * Oscillation Window
             * @default 4
             */
            oscillation_window?: number;
            /**
             * Oscillation Fwd Stop Max
             * @default 1
             */
            oscillation_fwd_stop_max?: number;
            /**
             * Turn In Place Lookahead M
             * @default 1
             */
            turn_in_place_lookahead_m?: number;
            /**
             * Lookahead M
             * @default 0.5
             */
            lookahead_m?: number;
            /**
             * Max Linear Mps
             * @default 0.5
             */
            max_linear_mps?: number;
            /**
             * Max Angular Radps
             * @default 1.0471975511965976
             */
            max_angular_radps?: number;
            /**
             * Rotate Threshold Deg
             * @default 30
             */
            rotate_threshold_deg?: number;
        };
        /** OnlineStep */
        OnlineStep: {
            /** Step Index */
            step_index: number;
            /** T Sim S */
            t_sim_s: number;
            /** Image */
            image: string;
            /** Instruction */
            instruction: string;
            /** Sector Trajectory */
            sector_trajectory: [
                number,
                number
            ][];
            /** World Trajectory */
            world_trajectory: [
                number,
                number
            ][];
            /** World Path */
            world_path: [
                number,
                number
            ][];
            /** Agent Position */
            agent_position: [
                number,
                number,
                number
            ];
            /** Agent Rotation */
            agent_rotation?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Instruction Info */
            instruction_info?: {
                [key: string]: unknown;
            };
            /**
             * Epoch
             * @default 0
             */
            epoch?: number;
            /** Actions */
            actions?: number[] | null;
            /** Linear Mps */
            linear_mps: number;
            /** Angular Radps */
            angular_radps: number;
            /** Inference Ms */
            inference_ms: number;
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
        };
        /** PredictionRequest */
        PredictionRequest: {
            /** Mode Id */
            mode_id: string;
            /** Domain Id */
            domain_id?: string | null;
            /** Model Id */
            model_id: string;
            /** Observation Id */
            observation_id: string;
            /** Image */
            image?: string | null;
            /** Instruction */
            instruction: string;
            /**
             * Start
             * @description Optional selected start; null uses the profile's standard inference start
             */
            start?: [
                number,
                number
            ] | null;
            /**
             * Grid Size
             * @default 24
             */
            grid_size?: number;
            /**
             * Max Steps
             * @default 100
             */
            max_steps?: number;
            /**
             * Policy Dt
             * @default 0.01
             */
            policy_dt?: number;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Sample Index */
            sample_index?: number | null;
            /**
             * Split
             * @default val
             */
            split?: string;
        };
        /** PredictionResult */
        PredictionResult: {
            /** Observation Id */
            observation_id: string;
            /** Model Id */
            model_id: string;
            /** Method */
            method: string;
            /** Profile */
            profile: string;
            /** Coordinate Frame */
            coordinate_frame: string;
            /** Coordinate Unit */
            coordinate_unit: string;
            /** Vector Unit */
            vector_unit: string;
            /** Queries */
            queries: [
                number,
                number
            ][];
            /** Vectors */
            vectors: [
                number,
                number
            ][];
            /** Trajectory */
            trajectory: [
                number,
                number
            ][];
            /** Stop Reason */
            stop_reason: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Cache Hit */
            cache_hit: boolean;
            /** Inference Rules */
            inference_rules?: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Actions */
            actions?: number[] | null;
            /** Action Semantics */
            action_semantics?: string | null;
        };
        /** RegisteredResource */
        RegisteredResource: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "model" | "dataset" | "benchmark";
            /** Resource Id */
            resource_id: string;
            /** Label */
            label: string;
            /** Path */
            path: string;
            /** Split */
            split?: string | null;
            /** Domain Id */
            domain_id?: string | null;
            /** Method */
            method?: string | null;
            /** Profile */
            profile?: string | null;
        };
        /** ResourceActivation */
        ResourceActivation: {
            /** Domain Id */
            domain_id: string;
            /** Split */
            split?: string | null;
        };
        /** ResourceBrowse */
        ResourceBrowse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "model" | "dataset" | "benchmark";
            /** Cwd */
            cwd: string;
            /** Parent */
            parent: string | null;
            /** Selectable */
            selectable: boolean;
            /** Selected Path */
            selected_path?: string | null;
            /** Entries */
            entries: components["schemas"]["BrowseEntry"][];
            /** Shortcuts */
            shortcuts: components["schemas"]["BrowseShortcut"][];
        };
        /** ResourceRegistration */
        ResourceRegistration: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "model" | "dataset" | "benchmark";
            /** Domain Id */
            domain_id?: string | null;
            /** Path */
            path: string;
            /** Label */
            label?: string | null;
            /**
             * Split
             * @default val
             */
            split?: string;
        };
        /** RuntimeDevice */
        RuntimeDevice: {
            /** Device */
            device: string;
            /** Gpu Available */
            gpu_available: boolean;
            /** Gpu Name */
            gpu_name?: string | null;
            failure?: components["schemas"]["DeviceFailure"] | null;
            /** Can Change */
            can_change: boolean;
        };
        /** SceneDescriptor */
        SceneDescriptor: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Url */
            url: string;
            /**
             * Up Axis
             * @default y
             * @enum {string}
             */
            up_axis?: "y" | "z";
            /** Floors */
            floors?: components["schemas"]["FloorSpec"][];
        };
        /** StudioClosed */
        StudioClosed: {
            /**
             * Status
             * @default closed
             * @constant
             */
            status?: "closed";
            /** Server Stopping */
            server_stopping: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    close_studio_api_v1_runtime_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudioClosed"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    runtime_device_api_v1_runtime_device_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeDevice"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    select_device_api_v1_runtime_device_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeDevice"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    resource_browser_api_v1_resources_browse_get: {
        parameters: {
            query: {
                kind: "model" | "dataset" | "benchmark";
                path?: string | null;
                domain_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceBrowse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    register_resource_api_v1_resources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceRegistration"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredResource"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activate_resource_api_v1_resources__kind___resource_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "model" | "dataset" | "benchmark";
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceActivation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredResource"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    scene_asset_api_v1_scenes__scene_id__asset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dataset_sample_api_v1_datasets__dataset_id__samples__index__get: {
        parameters: {
            query?: {
                split?: string;
                domain_id?: string | null;
            };
            header?: never;
            path: {
                dataset_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    predict_api_v1_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    benchmarks_api_v1_domains_ego2d_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineBenchmark"][];
                };
            };
        };
    };
    episodes_api_v1_domains_ego2d_benchmarks__benchmark_id__episodes_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                benchmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineEpisodePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenes_api_v1_domains_ego2d_benchmarks__benchmark_id__scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                benchmark_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineScenePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_domains_ego2d_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnlineSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_session_api_v1_domains_ego2d_sessions_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"] | null;
                };
            };
        };
    };
    session_api_v1_domains_ego2d_sessions__session_id__get: {
        parameters: {
            query?: {
                after_step?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_session_api_v1_domains_ego2d_sessions__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_session_api_v1_domains_ego2d_sessions__session_id__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnlineCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_session_api_v1_domains_ego2d_sessions__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_session_api_v1_domains_ego2d_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_session_api_v1_domains_ego2d_sessions__session_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnlineReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnlineSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
